---
- hosts: all
  tasks:
  - name: 1.1.14 - 1.1.16 Add noexec Option to /dev/shm Partition (Scored)
    mount: >
      name="/dev/shm"
      src="none"
      state=mounted
      fstype="tmpfs"
      opts="nodev,nosuid,noexec"
    tags:
      - section1.1
      - section1.1.14
      - section1.1.15
      - section1.1.16
      - scored

  - name: 1.5.5 Disable Interactive Boot (Scored)
    lineinfile: >
      dest=/etc/sysconfig/init
      regexp=^PROMPT=
      line=PROMPT=no
    tags:
      - scored
      - section1.5
      - section1.5.5

  - name: 1.6.1 Restrict core dumps (Scored) - via pam
    lineinfile: >
      dest=/etc/security/limits.conf
      line="* hard core 0"
      insertafter=EOF
    tags:
      - scored
      - section1.6
      - section1.6.1

  - name: 1.6.1 Restrict core dumps (Scored) - via sysctl
    sysctl: >
      name=fs.suid_dumpable
      value=0
      state=present
      ignoreerrors=yes
    tags:
      - scored
      - section1.6
      - section1.6.1

  - name: 1.6.2 Configure ExecShield (Scored)
    sysctl: >
      name=kernel.exec-shield
      value=1
      state=present
      ignoreerrors=yes
    tags:
      - scored
      - section1.6
      - section1.6.2

  - name: 1.6.3 Enable Randomized Virtual Memory Region Placement (Scored)
    sysctl: >
      name=kernel.randomize_va_space
      value=2
      state=present
      ignoreerrors=yes
    tags:
      - scored
      - section1.6
      - section1.6.3

  - name: 2.1.2 Remove telnet Clients (Scored)
    yum: >
      name=telnet
      state=absent
    tags:
      - scored
      - section2.1
      - section2.1.2

  - name: 3.1 Set Daemon umask (Scored)
    lineinfile: >
      dest=/etc/sysconfig/init
      state=present
      regexp=^umask
      line="umask 027"
    tags:
      - scored
      - section3.1

  - name: 3.8 Disable NFS and RPC (check for nfs-utils) (Not Scored)
    stat: path=/etc/init.d/nfslock
    register: nfs_utils
    tags:
      - notscored
      - section3.8

  - name: 3.8 Disable NFS and RPC (check for rpcbind) (Not Scored)
    stat: path=/etc/init.d/rpcbind
    register: rpcbind
    tags:
      - notscored
      - section3.8

  - name: 3.8 Disable NFS and RPC (nfs-utils services) (Not Scored)
    service: >
      name={{ item }}
      state=stopped
      enabled=no
    with_items:
      - nfslock
      - rpcgssd
      - rpcidmapd
      - rpcsvcgssd
    when: nfs_utils.stat.exists
    tags:
      - notscored
      - section3.8

  - name: 3.8 Disable NFS and RPC (rpcbind services) (Not Scored)
    service: >
      name=rpcbind
      state=stopped
      enabled=no
    when:
      - rpcbind.stat.exists
      - nfs
    tags:
      - notscored
      - section3.8

  - name: 3.10 Remove FTP Server (Not Scored)
    yum: >
      name=vsftpd
      state=absent
    when: ftp
    tags:
      - notscored
      - section3.10

  - name: 3.12 Remove Dovecot (IMAP and POP3 services) (Not Scored)
    yum: >
      name=dovecot
      state=absent
    when: dovecot
    tags:
      - notscored
      - section3.12

  - name: 3.13 Remove Samba (Not Scored)
    yum: >
      name=samba
      state=absent
    when: samba
    tags:
      - notscored
      - section3.13

  - name: 3.14 Remove HTTP Proxy Server (Not Scored)
    yum: >
      name=squid
      state=absent
    when: squid
    tags:
      - notscored
      - section3.14

  - name: 3.15 Remove SNMP Server (Not Scored)
    yum: >
      name=net-snmp
      state=absent
    when: snmp
    tags:
      - notscored
      - section3.15

  - name: 4.1.1 Disable IP Forwarding (Scored)
    sysctl: >
      name=net.ipv4.ip_forward
      value=0
      state=present
    tags:
      - scored
      - section4.1
      - section4.1.1

  - name: 4.1.2 Disable Send Packet Redirects (Scored)
    sysctl: >
      name=net.ipv4.conf.all.send_redirects
      value=0
      state=present
      ignoreerrors=true
    tags:
      - scored
      - section4.1
      - section4.1.2

  - name: 4.1.2 Disable Send Packet Redirects (Scored)
    sysctl: >
      name=net.ipv4.conf.default.send_redirects
      value=0
      state=present
      ignoreerrors=true
    tags:
      - scored
      - section4.1
      - section4.1.2

  - name: 4.2.1 Disable Source Routed Packet Acceptance (Scored)
    sysctl: >
      name=net.ipv4.conf.all.accept_source_route
      value=0
      state=present
      ignoreerrors=true
    tags:
      - scored
      - section4.2
      - section4.2.1

  - name: 4.2.1 Disable Source Routed Packet Acceptance (Scored)
    sysctl: >
      name=net.ipv4.conf.default.accept_source_route
      value=0
      state=present
      ignoreerrors=true
    tags:
      - scored
      - section4.2
      - section4.2.1

  - name: 4.2.2 Disable ICMP Redirect Acceptance (Scored)
    sysctl: >
      name=net.ipv4.conf.all.accept_redirects
      value=0
      state=present
      ignoreerrors=true
    tags:
      - scored
      - section4.2
      - section4.2.2

  - name: 4.2.2 Disable ICMP Redirect Acceptance (Scored)
    sysctl: >
      name=net.ipv4.conf.default.accept_redirects
      value=0
      state=present
      ignoreerrors=true
    tags:
      - scored
      - section4.2
      - section4.2.2

  - name: 4.2.4 Log Suspicious Packets (Scored)
    sysctl: >
      name=net.ipv4.conf.all.log_martians
      value=1
      state=present
      ignoreerrors=true
    tags:
      - scored
      - section4.2
      - section4.2.4

  - name: 4.2.4 Log Suspicious Packets (Scored)
    sysctl: >
      name=net.ipv4.conf.default.log_martians
      value=1
      state=present
      ignoreerrors=true
    tags:
      - scored
      - section4.2
      - section4.2.4

  - name: 4.2.5 Enable Ignore Broadcast Requests (Scored)
    sysctl: >
      name=net.ipv4.icmp_echo_ignore_broadcasts
      value=1
      state=present
      ignoreerrors=true
    tags:
      - scored
      - section4.2
      - section4.2.5

  - name: 4.2.6 Enable Bad Error Message Protection (Scored)
    sysctl: >
      name=net.ipv4.icmp_ignore_bogus_error_responses
      value=1
      state=present
      ignoreerrors=true
    tags:
      - scored
      - section4.2
      - section4.2.6

  - name: 4.4.1.1 Disable IPv6 Router Advertisements (Not Scored)
    sysctl: >
      name=net.ipv6.conf.all.accept_ra
      value=0
      state=present
      ignoreerrors=true
    tags:
      - notscored
      - section4.4
      - section4.4.1
      - section4.4.1.1

  - name: 4.4.1.1 Disable IPv6 Router Advertisements (Not Scored)
    sysctl: >
      name=net.ipv6.conf.default.accept_ra
      value=0
      state=present
      ignoreerrors=true
    tags:
      - notscored
      - section4.4
      - section4.4.1
      - section4.4.1.1

  - name: 4.4.1.2 Disable IPv6 Redirect Acceptance (Not Scored)
    sysctl: >
      name=net.ipv6.conf.all.accept_redirects
      value=0
      state=present
      ignoreerrors=true
    tags:
      - notscored
      - section4.4
      - section4.4.1
      - section4.4.1.2

  - name: 4.4.1.2 Disable IPv6 Redirect Acceptance (Not Scored)
    sysctl: >
      name=net.ipv6.conf.default.accept_redirects
      value=0
      state=present
      ignoreerrors=true
    tags:
      - notscored
      - section4.4
      - section4.4.1
      - section4.4.1.2

  - name: 4.4.2 Disable IPv6 (flush routes) (Not Scored)
    command: /sbin/sysctl -w net.ipv6.route.flush=1
    ignore_errors: yes
    when: disable_ipv6
    tags:
      - notscored
      - section4.4
      - section4.4.2

  - name: 4.5.2 Create /etc/hosts.allow (Not Scored)
    lineinfile: >
      state=present
      create=yes
      dest=/etc/hosts.allow
      regexp=^ALL
      line=ALL:{{ tcp_allow | default("ALL") }}
    tags:
      - notscored
      - section4.5
      - section4.5.2

  - name: 4.5.3 Verify Permissions on /etc/hosts.allow (Scored)
    file: >
      path=/etc/hosts.allow
      mode=0644
    tags:
      - scored
      - section4.5
      - section4.5.3

  - name: 4.5.4 Create /etc/hosts.deny (Not Scored)
    lineinfile: >
      state=present
      create=yes
      dest=/etc/hosts.deny
      line=ALL:ALL
    tags:
      - notscored
      - section4.5
      - section4.5.4

  - name: 4.5.5 Verify Permissions on /etc/hosts.deny (Scored)
    file: >
      path=/etc/hosts.deny
      mode=0644
    tags:
      - scored
      - section4.5
      - section4.5.5

  - name: 4.6.1 Disable DCCP (Not Scored)
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/CIS.conf
      line="install dccp /bin/true"
    tags:
      - notscored
      - section4.6
      - section4.6.1

  - name: 4.6.2 Disable SCTP (Not Scored)
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/CIS.conf
      line="install sctp /bin/true"
    tags:
      - notscored
      - section4.6
      - section4.6.2

  - name: 4.6.3 Disable RDS (Not Scored)
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/CIS.conf
      line="install rds /bin/true"
    tags:
      - notscored
      - section4.6
      - section4.6.3

  - name: 4.6.4 Disable TIPC (Not Scored)
    lineinfile: >
      state=present
      create=yes
      dest=/etc/modprobe.d/CIS.conf
      line="install tipc /bin/true"
    tags:
      - notscored
      - section4.6
      - section4.6.4


  - name: 4.7 Enable IPtables (Scored)
    service: >
      name=iptables
      enabled=yes
      state=started
    when: enable_iptables
    tags:
      - scored
      - section4.7

  - name: 4.8 Enable IP6tables (Not Scored)
    service: >
      name=ip6tables
      enabled=yes
      state=started
    ignore_errors: yes
    when: enable_ip6tables
    tags:
      - notscored
      - section4.8

  - name: 6.2.2 Set LogLevel to INFO (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^LogLevel "
      line="LogLevel INFO"
    notify: Reload sshd
    tags:
      - scored
      - section6.2
      - section6.2.2

  - name: 6.2.4 Disable SSH X11 Forwarding (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^X11Forwarding "
      line="X11Forwarding no"
    notify: Reload sshd
    tags:
      - scored
      - section6.2
      - section6.2.4

  - name: 6.2.5 Set SSH MaxAuthTries to 3 or Less (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^MaxAuthTries "
      line="MaxAuthTries 3"
    notify: Reload sshd
    tags:
      - scored
      - section6.2
      - section6.2.5

  - name: 6.2.6 Set SSH IgnoreRhosts to Yes (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^IgnoreRhosts "
      line="IgnoreRhosts yes"
    notify: Reload sshd
    tags:
      - scored
      - section6.2
      - section6.2.6

  - name: 6.2.7 Set SSH HostbasedAuthentication to No (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^HostbasedAuthentication "
      line="HostbasedAuthentication no"
    notify: Reload sshd
    tags:
      - scored
      - section6.2
      - section6.2.7

  - name: 6.2.8 Disable SSH Root Login (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^PermitRootLogin "
      line="PermitRootLogin no"
    notify: Reload sshd
    tags:
      - scored
      - section6.2
      - section6.2.8

  - name: 6.2.9 Set SSH PermitEmptyPasswords to No (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^PermitEmptyPasswords "
      line="PermitEmptyPasswords no"
    notify: Reload sshd
    tags:
      - scored
      - section6.2
      - section6.2.9

  - name: 6.2.10 Do Not Allow Users to Set Environment Options (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^PermitUserEnvironment "
      line="PermitUserEnvironment no"
    notify: Reload sshd
    tags:
      - scored
      - section6.2
      - section6.2.10

  - name: 6.2.11 Use Only Approved Cipher in Counter Mode (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^Ciphers "
      line="Ciphers aes128-ctr,aes192-ctr,aes256-ctr"
    notify: Reload sshd
    tags:
      - scored
      - section6.2
      - section6.2.11

  - name: 6.2.12 Set Idle Timeout Interval for User Login (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^ClientAliveInterval "
      line="ClientAliveInterval 900"
    notify: Reload sshd
    tags:
      - scored
      - section6.2
      - section6.2.12

  - name: 6.2.12 Set Idle Timeout Interval for User Login (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^ClientAliveCountMax "
      line="ClientAliveCountMax 0"
    notify: Reload sshd
    tags:
      - scored
      - section6.2
      - section6.2.12

  - name: 6.2.13 Limit Access via SSH (Scored)
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^AllowGroups "
      line="AllowGroups {{ ssh_allow_groups }}"
    when: ssh_allow_groups is defined
    notify: Reload sshd
    tags:
      - scored
      - section6.2
      - section6.2.13

  - name: 6.3.2 - 6.3.4 Configure PAM (Scored)
    copy: >
      src=etc/pam.d/system-auth
      dest=/etc/pam.d/system-auth
    tags:
      - scored
      - section6.3
      - section6.3.2
      - section6.3.3
      - section6.3.4

  - name: 7.1.3 Set Password Expiring Warning Days (Scored)
    lineinfile: >
      backup=yes
      state=present
      dest=/etc/login.defs
      backrefs=yes
      regexp="^PASS_WARN_AGE\s+"
      line="PASS_WARN_AGE\t7"
    tags:
      - scored
      - section7.1
      - section7.1.3

  - name: 7.2 Disable System Accounts (Scored) - preparation
    shell: awk -F':' '($3<500 && $1!="root" && $1!="sync" && $1!="shutdown" && $1!="sync" && $1!="shutdown" && $1!="halt" && $7!="/sbin/nologin") { print $1 }' /etc/passwd
    register: enabled_system_accounts
    changed_when: false
    tags:
      - scored
      - section7.2

  - name: 7.2 Disable System Accounts (Scored)
    command: /usr/sbin/usermod -s /sbin/nologin {{ item }}
    with_items: enabled_system_accounts.stdout_lines
    tags:
      - scored
      - section7.2

